# Generated by Django 3.2.7 on 2021-09-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
