# Generated by Django 3.2.7 on 2021-09-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
