# Generated by Django 3.2.7 on 2021-09-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('faculty', '0009_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='books',
            field=models.ManyToManyField(to='library.Book'),
        ),
    ]
